CEExpress_LOP/ViewModels/OrdersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using LOP_DatabaseModel.Model;

namespace CEExpress_LOP.ViewModels
{
    public class OrdersViewModel
    {
        public Order Order { get; set; }
        public PickupStop PickupStop { get; set; }
        public DeliverStop DeliverStop { get; set; }
    }
}

CEExpress_LOP/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CEExpress_LOP.App_Start;
using CEExpress_LOP.Core;
using CEExpress_LOP.Core.Repository;
using CEExpress_LOP.Models;
using CEExpress_LOP.ViewModels;
using LOP_DatabaseModel.Model;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace CEExpress_LOP.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private IOrderRepository orderRepo;

        public OrdersController()
        {
            this.orderRepo = new OrderRepository(new CEExpressDBEntities());
        }
        
        [Authorize]
        // GET: Orders
        public ActionResult Index(string sortRequest, string searchString, string currentOrderFilter)
        {

            ViewBag.CurrentSort = sortRequest;

            ViewBag.OrderNumberSort = String.IsNullOrEmpty(sortRequest) ? "orderNum_desc" : "";
            ViewBag.CustNumSort = sortRequest == "Customer Number" ? "custNumber_desc" : "Customer Number";
            ViewBag.CostCenterSort = sortRequest == "Cost Centre" ? "costCenter_desc" : "Cost Centre";
            ViewBag.StatusDateSort = sortRequest == "Status Date" ? "statusDate_desc" : "Status Date";
            ViewBag.StatusSort = sortRequest == "Status" ? "status_desc" : "Status";

            if (searchString != null)
            {
                
            }
            else
            {
                searchString = currentOrderFilter;
            }

            ViewBag.CurrentFilter = searchString;


            //Clients can see their history of orders placed.
            return View(orderRepo.GetCustOrdersWithSortRequest(sortRequest, GetCustNum(), searchString, currentOrderFilter));
        }

        // GET: Orders/Details/id
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = orderRepo.GetOrderByID(id);
            if (order == null)
            {
                return HttpNotFound();
            }

            //Do a check to make sure that the order belongs to the Customer logged in or Management
            if (order.customer_number.Equals(GetCustNum()) || User.IsInRole("Management"))
            {
                return View(order);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        // GET: Orders/NewOrderView
        public ActionResult NewOrderView()
        {
            return View();
        }

        // POST: Orders/NewOrderView
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NewOrderView(OrdersViewModel orderVM)
        {
            if (ModelState.IsValid)
            {
                //Create the order object from the placed Order details
                Order o = new Order();
                o.customer_number = GetCustNum();
                o.cost_center = "AJ Omnicare";
                o.order_type = "Pickup";

                o.PickupStop = orderVM.PickupStop;
                o.DeliverStop = orderVM.DeliverStop;

                //Prepare the order object to be sent to the api
                string ApiPayload = PrepareOrderAsStringPayload(o);


                if (SubmitToAPI(ApiPayload))
                {
                    //If it is true, then we know the order was submitted successfully and we can view the details of it
                    return RedirectToAction("Details", new { id = TempData["orderId"] } );
                }
                else
                {   //If the SubmitToAPI Was false, there was a problem in submitting the order.
                    ModelState.AddModelError(string.Empty, "An Error occured while attempting to submit this order. Please try again later.");
                    return View(orderVM);
                }
            }
            //If this is thrown, the model state was not valid, and has errors before submission can be made.
            return View(orderVM);
        }

        public ActionResult Track(int? id)
        {
            if(id != null)
            {
                return View(orderRepo.GetOrderByID(id).DeliverStop);
            }
            else
            {
                return HttpNotFound();
            }
        }


        protected override void Dispose(bool disposing)
        {
            orderRepo.Dispose();
            base.Dispose(disposing);
        }

        private bool SubmitToAPI(string postPayload)
        {
            try
            {
                APIConnection api = new APIConnection(APIConnection.GetAPIKey(), APIConnection.GetCID(), GetCustNum(), "https://api.dwaybill.com/");

                //Get the result from the API Posting
                string[] result = api.PostPayloadAsync(postPayload).Result;
                //Check to see what the result of the API communication was
                if (int.Parse(result[0]) == (int)HttpStatusCode.OK && result[2] != null)
                {
                    //We now need to retrieve the posted order to get all of the new information added to it. 
                    Order order = GetOrderFromAPIPayload(int.Parse(result[2]), GetCustNum());

                    //Check if order is null, if it is, we absolutely don't want that going into the Database 
                    if (order != null)
                    {
                        //Add the order to our local database
                        return InsertOrderIntoDatabase(order);
                    }
                    else
                    {
                        // An Error occured and Order is null, do not insert it into the database
                        return false;                  
                    }
                }
                else if (result[0].Equals("-1"))
                {
                    //There was an API Communication result exception
                    System.Diagnostics.Debug.WriteLine("Error in SUBMIT_TO_API (GenEx): " + result[1] );
                    return false;
                }
                else
                {
                    //The order was not posted successfully in this case, or there was an error
                    return false;
                }
            }
            catch (Exception)
            {
                //If an exception was thrown, handle it here. We need to return false since the SubmitToApi was unsuccessful
                return false;
            }     
        }

        private string GetCustNum()
        {
            var mgr = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();

            var user = mgr.FindById(User.Identity.GetUserId());

            return user.UserName;
        }

        private bool InsertOrderIntoDatabase(Order order)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    orderRepo.InsertOrder(order);
                    orderRepo.Save();

                    TempData["orderId"] = order.orderId;
                    return true;
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name after DataException and add a line here to write a log.
                return false;
            }

            return false;
        }

        private string PrepareOrderAsStringPayload(Order order)
        {
           PayloadProcessor p = new PayloadProcessor();
           return p.CreatePayload(order);
        }

        public ActionResult CheckOrderUpdates()
        {
            if (orderRepo.CheckAndUpdateOrders(orderRepo.GetOrders(GetCustNum()), GetCustNum()))
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Contact", "Home");
            
        }

        private Order GetOrderFromAPIPayload(int orderNumber, string customerNumber)
        {
            try
            {
                APIConnection Conn = new APIConnection(APIConnection.GetAPIKey(), APIConnection.GetCID(), customerNumber, "https://api.dwaybill.com/");
                string orderPayloadReceived = Conn.GetAPIPayloadAsync(orderNumber).Result;
                //Check to see if there is a null order string
                if (orderPayloadReceived != null)
                {
                    PayloadProcessor p = new PayloadProcessor();
                    return p.ProcessPayloadRecieved(orderPayloadReceived);
                }
                else
                {
                    //Return as there is indeed no order due to an error
                    return null;
                }
            }
            catch(Exception)
            {
                //If there was an Order API Retrieve exception, continue to throw the null back up as there is no order to work with
                return null;
            }            
        }
    }
}

CEExpress_LOP/Views/Orders/Details.cshtml
@model LOP_DatabaseModel.Model.Order

@{
    ViewBag.Title = "Order Details";
}

<head>

    <!--google tracking code for analytics-->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-128479113-2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-128479113-2');
    </script>

</head>

<div class="container">
    @*<div class="container formHeaders">
            <h2>Details</h2>
        </div>*@


    <div class="container-fluid no-gutters indexCaption  form-header text-center mb-0">
        @*<caption>*@
        <h4 class="m-0">Details For Order: @Html.DisplayFor(model => model.order_number) </h4>
        @*</caption>*@
    </div>


    <div class="container justify-content-center p-0">

        <div class="row justify-content-center">
            <div class="col-md-11">
                @*Details Section*@
                <table class="table table-responsive table-hover table-md table-bordered w-auto">
                    <thead class="table-warning">
                        <tr>
                            <th >
                                @Html.DisplayNameFor(model => model.time)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.customer_number)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.final_price)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.status_date)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ready_time)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.deliver_by)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.status)
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                @Html.DisplayFor(model => model.time)
                            </td>
                            <td>
                                @Html.DisplayFor(model => model.customer_number)
                            </td>
                            <td>
                                @Html.DisplayFor(model => model.final_price)
                            </td>
                            <td>
                                @Html.DisplayFor(model => model.status_date)
                            </td>
                            <td>
                                @Html.DisplayFor(model => model.ready_time)
                            </td>
                            <td>
                                @Html.DisplayFor(model => model.deliver_by)
                            </td>
                            <td>
                                @Html.DisplayFor(model => model.status)
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <h4 id="pickUpStopDetailsTitle" data-toggle="collapse" data-target="#pickUpStopDetails">PickupStop</h4>
        <div class="row justify-content-center collapse" id="pickUpStopDetails">
            <div class="col-md-8">

                @*PickUp Section*@
                @Html.Partial("_PickupStopDetails", Model.PickupStop)
            </div>
        </div>

        <h4 id="deliveryStopDetailsTitle" data-toggle="collapse" data-target="#deliveryStopDetails">DeliverStop</h4>
        <div class="row justify-content-center collapse" id="deliveryStopDetails">
            <div class="col-md-8">
                @*DeliveryStop Section*@
                @Html.Partial("_DeliverStopDetails", Model.DeliverStop)
            </div>
        </div>


        @*<div class="row justify-content-center">
                <div class="col-md-6">

                    @Html.Partial("_PickupStopDetails", Model.PickupStop)
                </div>
                <div class="col-md-6">

                    @Html.Partial("_DeliverStopDetails", Model.DeliverStop)
                </div>
            </div>*@
    </div>
    <div class="row justify-content-end m-0 p-0">
        @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-info m-0 mb-2" })

    </div>
</div>

CEExpress_LOP/Views/Orders/Index.cshtml
@model IEnumerable<LOP_DatabaseModel.Model.Order>

@{
    ViewBag.Title = "Index";
}

<head>

    <!--google tracking code for analytics-->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-128479113-2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-128479113-2');

    </script>


    <style>
       
    </style>
</head>

@*<div class="container">*@
    @*///the gutters dont go all the way do to the cointaner, though if cointainer has no gutters it falls to the left*@
    @*<div class="container-fluid formHeaders no-gutters">
        <div class="row no-gutters r">*@
            @*<div class="col-md-10">
             @*   <h3</h3>*@
          @*  </div>*@
            @*<div class="col-md-2">
                <p class="align-self-center">
                </p>
            </div>*@
        @*</div>*@
    @*</div>*@
<div class="container">

    <div class=" table-striped table-bordered table-hover">
        <div class="container-fluid no-gutters indexCaption  form-header text-center mb-0">
            @*<caption>*@
            <h4>Order History </h4>
            @*</caption>*@
        </div>
        <div class="row">
            <div class="col-md-6">
                @using (Html.BeginForm("Index", "Orders", FormMethod.Get))
                {
                    <p>
                        @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @placeholder = " Order Search Query" })
                        <input class="btn btn-default" type="submit" value="Search" />
                    </p>


                }
            </div>

            <div class="col-md-4"></div>
            <div class="col-md-1">

                @Html.ActionLink("Refresh", "CheckOrderUpdates", null, new { @class = "btn btn-default" })
            </div>
            <div class="col-md-1">

                <button class="btn btn-default hidden-print" onclick="window.print()"> Print</button>

            </div>
        </div>
        <table class="table">
            <thead class="table-warning">
                <tr>
                    <th>
                        @Html.ActionLink(Html.DisplayNameFor(model => model.order_number).ToString(), "Index", new { sortRequest = ViewBag.OrderNumberSort, currentOrderFilter = ViewBag.CurrentFilter })
                    </th>
                    <th>
                        @Html.ActionLink(Html.DisplayNameFor(model => model.customer_number).ToString(), "Index", new { sortRequest = ViewBag.CustNumSort, currentOrderFilter = ViewBag.CurrentFilter })
                    </th>
                    <th>
                        @Html.ActionLink(Html.DisplayNameFor(model => model.cost_center).ToString(), "Index", new { sortRequest = ViewBag.CostCenterSort, currentOrderFilter = ViewBag.CurrentFilter })
                    </th>

                    <th>
                        @Html.ActionLink(Html.DisplayNameFor(model => model.status_date).ToString(), "Index", new { sortRequest = ViewBag.StatusDateSort, currentOrderFilter = ViewBag.CurrentFilter })
                    </th>
                    <th>
                        @Html.ActionLink(Html.DisplayNameFor(model => model.status).ToString(), "Index", new { sortRequest = ViewBag.StatusSort, currentOrderFilter = ViewBag.CurrentFilter })
                    </th>
                </tr>
            </thead>

            @*tbody not neccessaey seems like its generated mvc*@
            <tbody>
                @foreach (var item in Model)
                {

                    <tr>
                        <td>
                            @Html.ActionLink(item.order_number.ToString(), "Details", new { id = item.orderId })
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.customer_number)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.cost_center)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.status_date)
                        </td>
                        <td>
                            @Html.ActionLink(item.status.ToString(), "Track", new { id = item.orderId })
                        </td>

                    </tr>

                }
            </tbody>
        </table>


    </div>
</div>

CEExpress_LOP/Views/Orders/NewOrderView.cshtml
@model CEExpress_LOP.ViewModels.OrdersViewModel

@{
    ViewBag.Title = "NewOrderView";
}


<head>

    <!--google tracking code for analytics-->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-128479113-2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-128479113-2');
    </script>

</head>



<div class="container">
        
    <div class="row justify-content-center ">   
        

        <div class="col-md-6 bg-light p-4 rounded mt-3 form-width">
            <center>
                <h4 class="form-header text-center">New Order</h4>
            </center>
            <!--server respoense-->
            <h5 class="text-center text-light bg-success mb-2 p-2 rounded lead" id="result">
                Hello World!
            </h5>
            <!--progress bar-->
            <div id="progressBarBack " class="progress mb-2" style="height:40px;">
                <div class="progress-bar bg-danger" role="progressbar" style="width:25%;" id="progressBar">
                    <b class="lead" id="progressText">Step-1</b>
                </div>
            </div>
            @using (Html.BeginForm(FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @*///the gutters dont go all the way do to the cointaner, though if cointainer has no gutters it falls to the left*@
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <!--firstpage-->
                <div id="first">
                    <!--cart steps-->
                    <div class="cart-steps">
                        <ul class="row">
                            <li class="cartStep1 col-sm-3 active">
                                <a @*class="cartStep1"*@ href="#"><span>1</span>Pick Up Information</a>
                            </li>
                            <li class="col-sm-3"><span>2</span>Package Information</li>
                            <li class="col-sm-3"><span>3</span>Delivery Information</li>
                            <li class="col-sm-3"><span>4</span>Summary</li>
                        </ul>
                    </div>

                    <h4 class="cartBar text-center bg-primary p-1 rounded text-light">Pick Up Information</h4>

                    <!--inputs-->
                    @Html.Partial("_PickUpStopNewOrder")

                    <!--cart buttons-->
                    <div class="row form-group justify-content-end">
                        <a class="btn btn-danger" id="next_1">Next</a>
                    </div>
                </div>

                <!--secondpage-->
                <div id="second">
                    <!--cart steps-->
                    <div class="cart-steps">
                        <ul class="row">
                            <li class="cartStep1 col-sm-3 active">
                                <a @*class="cartStep1"*@ href="#"><span>1</span>Pick Up Information</a>
                            </li>
                            <li class="cartStep2 col-sm-3 active">
                                <a @*class="cartStep2"*@ href="#"><span>2</span>Package Information</a>
                            </li>
                            <li class="col-sm-3"><span>3</span>Delivery Information</li>
                            <li class="col-sm-3"><span>4</span>Summary</li>
                        </ul>
                    </div>

                    <h4 class="cartBar text-center bg-primary p-1 rounded text-light">Package Information</h4>

                    <!--inputs-->
                    @Html.Partial("_PackageInfoNewOrder")

                    <!--cart buttons-->
                    <div class="row form-group justify-content-between">
                        <a class="btn btn-danger" id="previous_2">Previous</a>
                        <a class="btn btn-danger" id="next_2">Next</a>
                    </div>
                </div>

                <!--thirdpage-->
                <div id="third">
                    <!--cart steps-->
                    <div class="cart-steps">
                        <ul class="row">
                            <li class="cartStep1 col-sm-3 active">
                                <a @*class="cartStep1"*@ href="#"><span>1</span>Pick Up Information</a>
                            </li>
                            <li class="cartStep2 col-sm-3 active">
                                <a @*class="cartStep2"*@ href="#"><span>2</span>Package Information</a>
                            </li>
                            <li class="cartStep3 col-sm-3 active">
                                <a @*class="cartStep3"*@ href="#"><span>3</span>Delivery Information</a>
                            </li>
                            <li class="col-sm-3"><span>4</span>Summary</li>
                        </ul>
                    </div>

                    <h4 class="cartBar text-center bg-primary p-1 rounded text-light">Delivery Information</h4>

                    <!--inputs-->
                    @Html.Partial("_DeliverStopNewOrder")

                    <!--cart buttons-->
                    <div class="row form-group justify-content-between">
                        <a class="btn btn-danger" id="previous_3">Previous</a>
                        <a class="btn btn-danger" id="next_3">Next</a>
                    </div>
                </div>

                <!--fourthpage-->
                <div id="fourth">
                    <!--cart steps-->
                    <div class="cart-steps">
                        <ul class="row">
                            <li class="cartStep1 col-sm-3 active">
                                <a @*class="cartStep1"*@ href="#"><span>1</span>Pick Up Information</a>
                            </li>
                            <li class="cartStep2 col-sm-3 active">
                                <a @*class="cartStep2"*@ href="#"><span>2</span>Package Information</a>
                            </li>
                            <li class="cartStep3 col-sm-3 active">
                                <a @*class="cartStep3"*@ href="#"><span>3</span>Delivery information</a>
                            </li>
                            <li class="cartStep4 col-sm-3 active">
                                <a @*class="cartStep4"*@ href="#"><span>4</span>Summary</a>
                            </li>
                        </ul>
                    </div>

                    <h4 class="cartBar text-center bg-primary p-1 rounded text-light">Confirm Order</h4>

                    <!--inputs-->
                        @Html.Partial("_ConfirmationNewOrder")
                    <!--buttons-->
                    <div class="row form-group justify-content-between">
                        <a class="btn btn-danger" id="previous_4">Previous</a>
                        <input id="placeOrder" type="submit" value="Place Order" class="btn btn-warning" />
                    </div>
                    @*Buttons*@
                    @*<div class="form-group">
            <div class="col-md-12 justify-content-center">
                <input id="placeOrder" type="submit" value="Place Order" class="btn btn-warning btn-block" />
            </div>
        </div>*@
                </div>

            }

        </div>

    </div>
</div>

CEExpress_LOP/Views/Orders/_DeliverStopNewOrder.cshtml
@model CEExpress_LOP.ViewModels.OrdersViewModel

<head>

    <!--google tracking code for analytics-->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-128479113-2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-128479113-2');
    </script>

</head>

<div class="form-group">
    @Html.LabelFor(model => model.DeliverStop.company, htmlAttributes: new { @class = "control-label col-md-10" })
    @Html.EditorFor(model => model.DeliverStop.company, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.DeliverStop.company, "", new { @class = "text-danger" })

</div>

<div class="form-group">
    @Html.LabelFor(model => model.DeliverStop.name, htmlAttributes: new { @class = "control-label col-md-10" })
    @Html.EditorFor(model => model.DeliverStop.name, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.DeliverStop.name, "", new { @class = "text-danger" })

</div>

<div class="form-group">
    @Html.LabelFor(model => model.DeliverStop.phone, htmlAttributes: new { @class = "control-label col-md-10" })
    @Html.EditorFor(model => model.DeliverStop.phone, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.DeliverStop.phone, "", new { @class = "text-danger" })

</div>

<div class="form-group">
    @Html.LabelFor(model => model.DeliverStop.address, htmlAttributes: new { @class = "control-label col-md-10" })
    @Html.EditorFor(model => model.DeliverStop.address, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.DeliverStop.address, "", new { @class = "text-danger" })

</div>

<div class="form-group">
    @Html.LabelFor(model => model.DeliverStop.suite, htmlAttributes: new { @class = "control-label col-md-10" })
    @Html.EditorFor(model => model.DeliverStop.suite, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.DeliverStop.suite, "", new { @class = "text-danger" })

</div>

<div class="form-group">
    @Html.LabelFor(model => model.DeliverStop.country, htmlAttributes: new { @class = "control-label col-md-10" })
    @Html.EditorFor(model => model.DeliverStop.country, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.DeliverStop.country, "", new { @class = "text-danger" })

</div>

<div class="form-group">
    @Html.LabelFor(model => model.DeliverStop.state, htmlAttributes: new { @class = "control-label col-md-10" })
    @Html.EditorFor(model => model.DeliverStop.state, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.DeliverStop.state, "", new { @class = "text-danger" })

</div>

<div class="form-group">
    @Html.LabelFor(model => model.DeliverStop.city, htmlAttributes: new { @class = "control-label col-md-10" })
    @Html.EditorFor(model => model.DeliverStop.city, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.DeliverStop.city, "", new { @class = "text-danger" })

</div>

<div class="form-group">
    @Html.LabelFor(model => model.DeliverStop.postal_code, htmlAttributes: new { @class = "control-label col-md-10" })
    @Html.EditorFor(model => model.DeliverStop.postal_code, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.DeliverStop.postal_code, "", new { @class = "text-danger" })

</div>