CEExpress_LOP/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CEExpress_LOP.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CEExpress_LOP/Controllers/ManagementController.cs
using CEExpress_LOP.App_Start;
using CEExpress_LOP.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CEExpress_LOP.Controllers
{
    [Authorize(Roles = "Management")]
    public class ManagementController : Controller
    {
        private ApplicationUserManager _userManager;

        // GET: Management
        public ActionResult Home()
        {
            return View();
        }

        public ActionResult ClientDetails()
        {
            if(TempData["register"] != null)
            {
                ViewData["register"] = TempData["register"];
            }

            try{
                    _userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
                    return View(_userManager.Users.ToList());
                }
                catch (Exception)
                {
                    ViewData["error"] = "There was an error in loading the client management page. Please refresh the page or try again later.";
                    return View();
                }
         
        }

        [HttpGet]
        public ActionResult Settings()
        {
            //Check if there is a status
            if(TempData["status"] != null)
            {
                ViewBag.Status = TempData["status"];
                TempData["status"] = null;
            }
            //When Displaying the settings page, pass it the setting values from web.config
            //Check to see if the cid and apikey settings exist and have values
            if(ConfigurationManager.AppSettings["cid"] != null && ConfigurationManager.AppSettings["apikey"] != null)
            {
                ViewBag.cid = ConfigurationManager.AppSettings["cid"];
                ViewBag.apikey = ConfigurationManager.AppSettings["apikey"];
            }
            else
            {
                ViewBag.cid = "Error! - CID Has not yet been set!";
                ViewBag.apikey = "Error! - API Key has not yet been provided!";
            }

            return View(ViewBag);
        }

        [HttpPost]
        public ActionResult UpdateSettings()
        {

            Configuration objConfig = System.Web.Configuration.WebConfigurationManager.OpenWebConfiguration("~");
            AppSettingsSection settings = (AppSettingsSection)objConfig.GetSection("appSettings");

            string cid = Request["cid"];
            string apikey = Request["apikey"];

            string oldCid = settings.Settings["cid"].Value;
            string oldApiKey = settings.Settings["apikey"].Value;

            try
            {
                bool modified = false;
                if (!cid.Equals(oldCid))
                {
                    settings.Settings["cid"].Value = cid;
                    modified = true;
                } 
                
                if(!oldApiKey.Equals(apikey))
                {
                    settings.Settings["apikey"].Value = apikey;
                    modified = true;
                }

                if (modified)
                {
                    objConfig.Save();
                   
                    return RedirectToAction("SettingsChanged");
                }
                TempData["status"] = "No settings were changed.";
            }
            catch (ConfigurationErrorsException)
            {
                TempData["status"] = "There was an error in updating the settings. Please try again later.";
            }

            return RedirectToAction("Settings");

        }

        public ActionResult SettingsChanged()
        {
            TempData["status"] = "The settings were successfully updated!";
            return RedirectToAction("Settings");
        }

        
        public ActionResult Analytics()
        {
            return View();
        }

        public ActionResult Reports()
        {
            return View();
        }
    }
}

CEExpress_LOP/Controllers/ReportsController.cs
using CEExpress_LOP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CEExpress_LOP.Controllers
{
    public class ReportsController : Controller
    {

        [Authorize(Roles ="Management")]
        public ActionResult ReportTemplate(string ReportName, string ReportDescription, int Width, int Height, string Class)
        {
            var rptInfo = new ReportSpecs
            {
                ReportName = ReportName,
                ReportDescription = ReportDescription,
                ReportURL = String.Format("../../Reporting/ReportingTemplate.aspx?ReportName={0}&Height={1}&Class={2}", ReportName, Height, Class ),
                Width = Width,
                Height = Height
            };

            return View(rptInfo);
        }

        
        public ActionResult ClientReportTemplate(string ReportName, string ReportDescription, int Width, int Height, string Class, string CustNumber)
        {
            var rptInfo = new ReportSpecs
            {
                ReportName = ReportName,
                ReportDescription = ReportDescription,
                ReportURL = String.Format("../../Reporting/ReportingTemplate.aspx?ReportName={0}&Height={1}&Class={2}&CustNumber={3}", ReportName, Height, Class, CustNumber),
                Width = Width,
                Height = Height
            };

            return View("ReportTemplate", rptInfo);
        }

    }
}

CEExpress_LOP/Views/Management/ClientDetails.cshtml
@model IEnumerable<CEExpress_LOP.Models.ApplicationUser>
@{
    ViewBag.Title = "Client Information";
}

<head>

    <!--google tracking code for analytics-->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-128479113-2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-128479113-2');
    </script>
</head>



<style>
    
</style>
<div class="container">
    @*<h4 class="form-header text-center">Management - Client Details</h4>*@
    <div class="col-11 m-auto">

        <div class="row">
            <div class="col-8"></div>
            <div class="col-4" style="">
            </div>
        </div>
        <form class="form-width" id="DetailsFormWidth">


            <i><b>@ViewData["register"]</b></i>

            @{
                if (@ViewData["error"] != null)
                {
                    <b>@ViewData["error"]</b>
                }
                else
                {
                    <h4 class="form-header text-center">Registered Clients</h4>
                    <div class="row">

                        <div class="col-md-2">
                            @Html.ActionLink("Register New Client", "Register", "Account", null, new { @class = "btn-default, btn" })
                        </div>

                        <div class="col-md-9">&nbsp;</div>
                        <div class="col-md-1">
                            <button class="btn btn-default hidden-print" onclick="window.print()"><span class="glyphicon glyphicon-print" aria-hidden="true"></span> Print</button>
                        </div>
                        </div>
                    @*<center><b class="text-center">These are clients which are registered to the portal:</b></center>*@
                    Html.RenderPartial("_ClientList", Model);
                    <hr />
                }
            }
        </form>
    </div>
</div>

CEExpress_LOP/Views/Management/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
}

<h2>Dashboard</h2>

<script>
    (function (w, d, s, g, js, fs) {
        g = w.gapi || (w.gapi = {}); g.analytics = { q: [], ready: function (f) { this.q.push(f); } };
        js = d.createElement(s); fs = d.getElementsByTagName(s)[0];
        js.src = 'https://apis.google.com/js/platform.js';
        fs.parentNode.insertBefore(js, fs); js.onload = function () { g.load('analytics'); };
    }(window, document, 'script'));
</script>



<div id="embed-api-auth-container"></div>
<div id="chart-container"></div>
<div id="view-selector-container"></div>


<script>

    gapi.analytics.ready(function () {

        /**
         * Authorize the user immediately if the user has already granted access.
         * If no access has been created, render an authorize button inside the
         * element with the ID "embed-api-auth-container".
         */
        gapi.analytics.auth.authorize({
            container: 'embed-api-auth-container',
            clientid: 'REPLACE WITH YOUR CLIENT ID'
        });


        /**
         * Create a new ViewSelector instance to be rendered inside of an
         * element with the id "view-selector-container".
         */
        var viewSelector = new gapi.analytics.ViewSelector({
            container: 'view-selector-container'
        });

        // Render the view selector to the page.
        viewSelector.execute();


        /**
         * Create a new DataChart instance with the given query parameters
         * and Google chart options. It will be rendered inside an element
         * with the id "chart-container".
         */
        var dataChart = new gapi.analytics.googleCharts.DataChart({
            query: {
                metrics: 'ga:sessions',
                dimensions: 'ga:date',
                'start-date': '30daysAgo',
                'end-date': 'yesterday'
            },
            chart: {
                container: 'chart-container',
                type: 'LINE',
                options: {
                    width: '100%'
                }
            }
        });


        /**
         * Render the dataChart on the page whenever a new view is selected.
         */
        viewSelector.on('change', function (ids) {
            dataChart.set({ query: { ids: ids } }).execute();
        });

    });
</script>

CEExpress_LOP/Views/Management/Home.cshtml
@using Microsoft.AspNet.Identity

@{
    //ViewBag.Title = "Home";
    var managementUser = User.Identity.GetUserName();
}

<head>

    <!--google tracking code for analytics-->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-128479113-2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-128479113-2');
    </script>

    </head>

    @*<h2>Home</h2>*@




@*<div class="row">
        <div class="col-md-1">
            space
        </div>

        <div class="col-md-2 a-1">
            @Html.ActionLink("Portal Settings", "Settings")
        </div>
        <div class="col-md-2 a-2">
            @Html.ActionLink("Client Details", "ClientDetails")
        </div>
        <div class="col-md-2 a-3">
            @Html.ActionLink("Management Reports", "Reports")
        </div>
        <div class="col-md-2 a-4">
            @Html.ActionLink("System Analytics", "Analytics")
        </div>

        <div class="col-md-1">
            space
        </div>
    </div>*@



@*<div class="row justify-content-center">
        <div class="col-md-1">
            space
        </div>
        <div class="col-md-10">
            <div class="element-1">Check and change API Settings for Digital Waybill</div>
            <div class="element-2">This is where the text description will go2</div>
            <div class="element-3">This is where the text description will go3</div>
            <div class="element-4">This is where the text description will go4</div>
        </div>
        <div class="col-md-1">
            space
        </div>
    </div>*@



<div class="col-md-8 m-auto pt-4" >
    
    <div id="RegisterFormWidth">
        <center>
            <h4 class="form-header text-center" id="formheader">@managementUser Home</h4>

            <i>
            <b></b>
            </i>

            <p>Here you can access quick actions and options to manage the application</p>

            <div class="container">
                <!--Option Menu Pills-->
                <ul class="nav nav-pills nav-fill justify-content-center m-2">
                    <li class="nav-item a-1 p-1">
                        @Html.ActionLink("Portal Settings", "Settings", null, new { @class = "nav-link", id = "a1" })
                    </li>
                    <li class="nav-item a-2 p-1">
                        @Html.ActionLink("Client Details", "ClientDetails", null, new { @class = "nav-link", id = "a2" })
                    </li>
                    <li class="nav-item a-3 p-1">
                        @Html.ActionLink("Management Reports", "Reports", null, new { @class = "nav-link", id = "a3" })
                    </li>
                    <li class="nav-item a-4 p-1">
                        @Html.ActionLink("System Analytics", "Analytics", null, new { @class = "nav-link", id = "a4" })
                    </li>
                </ul>

                <!--text displayed accordingly-->
                <div class="homeText row justify-content-center m-3 p-4">
                    <div class="col-md-10">
                        <div class="element-1"><b>Check and change API Settings for Digital Waybill</b></div>
                        <div class="element-2"><b>Check, Edit, and Delete Client Information.</b></div>
                        <div class="element-3"><b>View and Print Reports</b></div>
                        <div class="element-4"><b>Check C&amp;E Express' Traffic-Data.</b></div>
                    </div>
                </div>

            </div>



        </center>

    </div>


</div>




@*<hr />
        @Html.ActionLink("Portal Settings", "Settings") <br />
        @Html.ActionLink("Client Details", "ClientDetails") <br />
        @Html.ActionLink("Management Reports", "Reports")<br />
        @Html.ActionLink("System Analytics", "Analytics")<br />
    <hr />*@

CEExpress_LOP/Views/Management/Register.cshtml
@model CEExpress_LOP.ViewModels.RegisterViewModel
@{
    ViewBag.Title = "Register C&E Express Customer";
}

<head>

    <!--google tracking code for analytics-->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-128479113-2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-128479113-2');
    </script>

 </head>

    <h2>@ViewBag.Title.</h2>

    @using (Html.BeginForm("Register", "Account", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        <hr />
        @Html.ValidationSummary("", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-default" value="Register" />
            </div>
        </div>
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

CEExpress_LOP/Views/Management/Reports.cshtml
@{
    ViewBag.Title = "Reports";
}

<head>

    <!--google tracking code for analytics-->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-128479113-2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(3) { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-128479113-2');
    </script>
    <style>
    </style>

</head>

<div class="container" id="ReportsContainer">

    <center>
        <div class="col-md-8">
            <section class="form-width" id="ReportSection">
                 <h4 class="form-header text-center"> Management Reports</h4>

                <div class="accordion" id="ReportAccordion">
                    <div class="card">
                        <div class="card-header" id="headingOne">
                            <h5 class="mb-0">
                                <button class="btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                  Operational Efficiency Exception Report
                                </button>
                            </h5>
                        </div>

                        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#ReportAccordion">
                            <div class="card-body">
                                This report will showcase the number of orders recieved contrasted with the number of deliveries made to highlight operational efficiency.
                                <br />
                                <a class="btn btn-default" id="ReportUrl_ManagementException" href="@Url.Action("ReportTemplate", "Reports", new { ReportName = "Operational Efficiency Exception Report", ReportDescription = "Operational Efficiency Exception Report", Width = 100, Height = 800, Class="Management" })">
                                    Open Report
                                </a>

                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header" id="headingTwo">
                            <h5 class="mb-0">
                                <button class=" btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                   Monthly Revenue Report
                                </button>
                            </h5>
                        </div>
                        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#ReportAccordion">
                            <div class="card-body">
                                This report is coming soon!
                            </div>
                        </div>
                    </div>
                </div>


            </section>
        </div>


    </center>

</div>

CEExpress_LOP/Views/Management/Settings.cshtml
@{
    ViewBag.Title = "Portal Settings";
}


<head>

    <!--google tracking code for analytics-->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-128479113-2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-128479113-2');
    </script>

</head>

@*<h2>Management - System Settings Page</h2>*@



<div class="row" style="border-color: red; background-color:#f0f1f7;">


    <div class="col-lg-2"></div>
    <div class="col-lg-8">

            <div class="container" id="">
                <section class="form-width" id="">
                    <center>

                        <h4 class="form-header text-center" id="#">Digital Waybill API Set-up</h4>
                        <h5 style="color:red;" class="text-center" id="SettingsWarning">WARNING!</h5>
                        <center> <b class="text-center" style="color:orangered;"> Misconfiguration of these options can lead to functional issues in the portal. Updating these settings will cause the system to briefly reload.</b></center>
                        <hr />


                        <h5 class="text-center">Use this page to configure API access to Digital Waybill's services</h5>
                        <p class="text-center">Please ensure that these options are correctly configured as found form the Digital Waybill API and courier screens.</p>




                        @using (Html.BeginForm("UpdateSettings", "Management", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                        {
                        <div class="row">
                            <div class="col-md-3"></div>
                            <div class="col-md-2">
                                <label class="control-label"> Courier ID: </label>
                            </div>
                            @*<div class="col-md-1"></div>*@
                            <div class="col-md-5">

                                <input required id="cid" name="cid" value="@ViewBag.cid" placeholder=" Courrier ID: " /> <br />
                            </div>
                                <div class="col-md-2"></div>

                        </div>
                            <div class="row">
                                <div class="col-md-3"></div>
                                <div class="col-md-2">
                                    <label class="control-label"> API Key: </label>
                                </div>
                                <div class="col-md-5">

                                    <input id="apikey" name="apikey" value="@ViewBag.apikey" placeholder="Remote Panel API Key:" /><br />
                                </div>
                                <div class="col-md-2"></div>

                                @*<div class="col-md-1"></div>*@
                            </div>

                            <center>
                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <br />
                                        <input type="submit" class="btn btn-default" value="Update Setting Values" />
                                    </div>
                                </div>
                            </center>
                        }
                        <i>@ViewBag.status</i>
                    </center>

                </section>
            </div>

    </div>
    <div class="col-lg-2"></div>
</div>